[phases.setup]
nixPkgs = ["python3", "python3-pip", "gcc", "python3-dev", "libmysqlclient", "pkg-config"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn wsgi:app"